# Napojeni na SQL
sql:
  hostname: host
  port: 3306
  database: database
  username: user
  password: password

# Nastaveni SQL
settings:
  minimumConnections: 2
  maximumConnections: 5
  timeout: 30000

# Při povolení se budou psát logy do konzole!
debug: false

# Server pro ukládání dat
server: test

# Aktivace různých věcí pro logování do DB
logger:
  # Zda má plugin logovat a ukládat změny v VIP do DB (pouze lobby?)
  vip-status: false

  # Změny v Ekonomice (vyžaduje CraftEconomy 1.3+)
  economy-changes: false

  # Změny v Levels (vyžaduje CraftEconomy 1.2+)
  levels-change: false