name: CraftLogger
version: 1.3.0
description: Log everything
author: MrWakeCZ
main: cz.craftmania.logger.Main
depend:
  - LuckPerms
softdepend:
  - CraftEconomy
  - PlotSquared
  - VoteParty
  - Lands
api-version: '1.15'
